// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgrjctrtwtgqpniqtfmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNncmpjdHJ0d3RncXBuaXF0Zm1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDE4NTEsImV4cCI6MjA2MzExNzg1MX0.ImaGp608YYj9p31fUB_PjwTf4wbJV-D1M7LpYoJ2rqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);